# Generated by Django 4.2.3 on 2023-07-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posts',
            new_name='categories',
        ),
    ]
